### ISSUE TITLE
updated tagging in m3u doesn't refresh for previously played files in foobar2000

### ISSUE THREAD

**Issue by VideogameScrapbook** [losnoco/vgmstream#565] opened 2020-02-26 19:55 UTC
I am investigating whether the special m3u format supported by vgmstream can offer as a suitable replacement for m-TAGS. The special m3u format is described here:
https://github.com/losnoco/vgmstream#Tagging

As a test, I tried taking a copy of the PlayStation 2 Gitaroo Man !tags.m3u playlist and repurpose it for Smash Bros. Ultimate tags, changing the filename pointers from Gitaroo Man files to the filenames of Smash Bros. Ultimate files.

Initially I couldn't figure out why it wasn't loading tags for these files (which I had previously played with foobar2000), but it seems that the foobar library metadata (in this case of blank fields of previously played songs) was overriding the !tags.m3u information. It wasn't until I renamed the filenames or moved them to a different folder where the information was loading properly. But then when updating the tags to something else, the metadata stuck to what it was when the song was first loaded under the new filename/location.

I can't figure out a way to force refresh the m3u tag information of any previously played files, even after making sure to close foobar2000 completely and making sure no instances where in running in Task Manager. Can you please make sure that m3u tags are refreshed from the file upon the song playing, upon the file first being loaded into foobar2000 and/or at least when the m3u playlist is re-loaded?

**Comment by bnnm** [comment] 2020-02-26 21:19
When your tags are updated you need to force refresh like this: select files > `shift + right click` > `Tagging` > `Reload info from file(s).` (this is mentioned somewhere in the doc but I'll make it clearer).

Unfortunately this is a foobar defect that (AFAIK) we can't do anything about. IIRC foobar caches metadata until the file itself (not the external data) is changed somehow, and if the plugin reloads tags foobar just ignores them.

If somehow m-tags isn't affected by this I'm not sure what it'd be doing, and there is public source code I could check.

**Comment by VideogameScrapbook** [comment] 2020-02-27 05:10
I had tested m-TAGS as well and confirmed that when you make a change to the !.tags file in a text editor, the tag is updated as soon as you play the song again. Just to speculate on one way it could do it (if it's being done as efficiently as it seems), maybe it keeps in memory the last modify time upon loading the !.tags file, then re-checks it every time a new song plays, if it's modified, it reloads tags.

Anyway, this could be another thing to mention in the vgmstream readme for now in case nobody has a desire to improve the m3u support. Are you aware of any advantages the special M3U format has over m-TAGS?

**Comment by bnnm** [comment] 2020-02-27 22:22
The problem isn't vgmstream reloading tags (it already tries to), but simply that foobar ignores any tag update unless the media (song) file itself changes, by design ([>>](https://hydrogenaud.io/index.php?topic=113645.msg935619#msg935619)). It works fine with other players.

m-tags works seemingly because you load the !.tags file then it loads media files, so it knows the "parent" tag file changed. While vgmstream works inversely, it loads the media file (say song.adx), then it tries to apply external tags if found (you aren't forced to load the !tags.m3u to get tags, btw). Since song.adx never changes, tags can't be updated. But foo_external_tags seems to load tags like vgmstream does but also updates them correctly, so maybe it's possible somehow (foobar API is very complex and undocumented though).

However, having to refresh tags manually is just a small annoyance I think, since normally you just create the tag file once then leave it untouched.

As for advantages, since I'm not familiar with all that m-TAGS does, I'd rather list what I hoped to accomplish and you can judge:
- built-in into vgmstream, you don't need anything extra. This kind of tagging is so niche that I wanted to lower the entry bar as much as possible
- easy to share, you can just send the !tags.m3u file to others
- works with multiple players (several people use vgmstream without foobar)
- technically simple and quick to add in vgmstream's various plugins, code is easy to use. Porting m-tags/foo_external_tags into other players is likely a lot of work.
- based on m3u so it's easy to edit and understand, while familiar enough. Allow comments so I can document where I got the tags or how I decided on order or stuff
- allows loading !tags.m3u for pre-made OST-like order, or single files and tags still work
- extensible, so I can add special tags to reduce typing (like $AUTOTRACK)
- can configure vgmstream using "virtual txtp" (advanced function)
- open source, anybody can see how good or bad tag code is. Not a worthwhile point for most people, but something I appreciate.

Some negative points are:
- !tags.m3u file must reside in the same dirs as the files
- No editor so can't be created so easily (however personally I never edit mp3 tags in foobar, but use [mp3tag](https://www.mp3tag.de/en/index.html), so I'd rather have an external/personalized tool/editor so people with other players could still tag)
- Code isn't very optimized at the moment, but probably not noticeable
- Only works with vgmstream formats

**Comment by VideogameScrapbook** [comment] 2020-02-28 05:10
Thanks bnnm for your reasons, very interesting and makes a lot of sense from what you were personally most interested in! :) Your reasons are personally not as important to me for my own personal tags as being able to tag from foobar2000 and loading without the secret Shift command, but I'll definitely use your m3u format when others share in that format.

I too also use mp3tag for song tagging for most everything else. Could you explain how you would use mp3tag to create your format of m3u? Did you create an export script that you could share? If so and there is a wiki/repository of some kind to contribute to, then I'd be willing to switch over to the m3u format for my own tags as well.

**Comment by bnnm** [comment] 2020-03-01 11:43
There is no way to create special .m3u with mp3tag (it's in the "no editor" point...).

I mean that, just like I don't use foobar to tag mp3s, I would't use foobar to make m3u/external tags. It would be better to make a new specialized tool, similar to mp3tag, that would handle vgm formats.

That way it wouldn't be tied to a single player, and it could be programmed to read/write vgmstream's m3u, or m-tags format, or any others.

But since so few people use external tags there is little point to make such tool at this point.

**Comment by bnnm** [comment] 2020-04-05 21:39
Since I can't find a way to refresh tags from the plugin side I'll close this. I'll keep an eye though.

**Closed by bnnm** 2020-04-05 21:39 UTC
