### ISSUE TITLE
.sbr/.sbs is parsed incorrectly?

### ISSUE THREAD

**Issue by vergol** [losnoco/vgmstream#591] opened 2020-04-09 10:34 UTC
I'm checking FIFA 20 Switch audio files, most of them are .sbr/.sbs combinations, which is supported by vgmstream.
I also found .sbr_debug files, which, as I think, include sound names.
So I wanted to find out how that .sbr_debug is related to .sbr file, and connect sound names in .sbr_debug with sounds in .sbr.

So, here are files which I checked:
https://mega.nz/file/L0MnVYQQ#vBZFLL0SyBRvEpwuq5G1_3Gni40HL8_o11ygkXhO-vU

.sbr_debug is very similar to .sbr, but uses different sections (.SIZ instead of .OFF, .SRC with offset to sound names in data section, at offset +8).
I found 18 null-terminated names in .sbr_debug file.
When opening .sbr in Winamp, it shows 24 sounds - but you can see that some sounds are duplicated.
Then I checked the .sbs file itself, and by searching for "48 00 00 0C" header, I found only 18 occurences.
So could it be that .sbr parser is incorrect, and gives 24 sounds instead of 18?

**Comment by NicknineTheEagle** [comment] 2020-04-09 10:47
This is Harmony Sample Bank format, used in latest EA Sports games. The format was very confusing to begin with, I doubt I can improve the parser any further.
On a different note, where did extract these files from exactly? FIFA 20 uses Frostbite Engine on current gen platforms, does Switch get the same legacy version running on Ignite Engine as PS3/X360?

**Comment by vergol** [comment] 2020-04-09 10:54
Yes, Switch version is legacy version and uses .sbr/.sps with eaopus encoding.

Also, will be great if there will be a feature for vgmstream to export sound groups (DSET sections) and sound names.

**Comment by NicknineTheEagle** [comment] 2020-04-09 11:00
> Also, will be great if there will be a feature for vgmstream to export sound groups (DSET sections) and sound names.
I'm afraid that's not the purpose of vgmstream.

> sound groups (DSET sections)
Do you know something about this format?

**Comment by vergol** [comment] 2020-04-09 11:04
> I'm afraid that's not the purpose of vgmstream.
Why so? It'll be much more usable if you see sound names in Winamp, instead of just numbers.

> Do you know something about this format?
DSET sections are part of .sbr files, I think it stands for "data-set", so sounds in .sbr are kinda grouped.

**Comment by NicknineTheEagle** [comment] 2020-04-09 11:08
> Why so? It'll be much more usable if you see sound names in Winamp, instead of just numbers.

Ah, that's what you mean. Yes, it's most likely possible to use sbr_debug files to read names. I'll look into it at some point.

> DSET sections are part of .sbr files, I think it stands for "data-set", so sounds in .sbr are kinda grouped.

Yes, I got that part, was just wondering if you know more about this than I do.

As for duplicates, I've looked at the file and I'm seeing duplicate offsets within the same DSET section at 0x356. Doesn't seem like a flaw of the parser to me, I'm guessing the bank uses the same sound twice, maybe in a different way.

**Comment by vergol** [comment] 2020-04-09 11:13
Ok, thanks.
Here's some information about .sbr_debug files.

Comparison with .sbr:
![Image1](https://i.imgur.com/PI5BSPW.png) ![Image2](https://i.imgur.com/xmGoojj.png)

Sound names:
![Image3](https://i.imgur.com/twLpeHC.png) ![Image4](https://i.imgur.com/1Ds9pTc.png)

In files which I uploaded, there are 3 DSET sections.
In 2nd section, names offset is 4 (so points to null string) - so could be that this section is not used.

**Comment by vergol** [comment] 2020-04-09 12:55
@NicknineTheEagle can you please tell me in which order vgmstream extracts sounds from .sbr?
For uploaded files, the first extracted sound is a first sound in first DSET section, and 24th sound is the last sound in third DSET section?

**Comment by NicknineTheEagle** [comment] 2020-04-09 12:57
Yes, it just reads the sounds in the order they're listed in DSET sections.

**Comment by NicknineTheEagle** [comment] 2020-04-10 09:32
Closing since the original issue of duplicate sounds is resolved.

**Closed by NicknineTheEagle** 2020-04-10 09:32 UTC

**Comment by NicknineTheEagle** [comment] 2020-11-07 13:50
@vergol Do you have any sbr/sbs samples with RAM sounds inside sbr? I need to check something and I really don't want to dump FIFA games all over again.
